import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { render, screen, waitFor, fireEvent } from "@testing-library/react";
import App from "./App";

const meta = {
	generated_at_utc: "2026-08-16T00:00:00Z",
	default_model: "test-model-xyz",
	default_prompt_version: "v1",
	default_schema_version: "s1",
	incident_count: 0,
};

function mockFetchOnce(ok: boolean, body?: unknown) {
	return vi.fn().mockResolvedValueOnce({ ok, status: ok ? 200 : 500, json: async () => body });
}

describe("App", () => {
	beforeEach(() => {
		vi.stubGlobal(
			"fetch",
			vi.fn((url: string) => {
				if (url.includes("meta.json")) return Promise.resolve({ ok: true, json: async () => meta });
				if (url.includes("incidents.json")) return Promise.resolve({ ok: true, json: async () => [] });
				if (url.includes("coverage.json")) return Promise.resolve({ ok: true, json: async () => [] });
				return Promise.reject(new Error("unexpected url"));
			}),
		);
	});

	afterEach(() => {
		vi.unstubAllGlobals();
	});

	it("shows a loading skeleton before data resolves", () => {
		render(<App />);
		expect(screen.getByRole("status", { name: /loading incident data/i })).toBeTruthy();
	});

	it("renders the provenance bar once data resolves", async () => {
		render(<App />);
		await waitFor(() => expect(screen.getByText(/summaries generated by/i)).toBeTruthy());
		expect(screen.getAllByText("test-model-xyz").length).toBeGreaterThan(0);
	});

	it("shows a retry-able error state when the fetch fails", async () => {
		vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("network down")));
		render(<App />);
		await waitFor(() => expect(screen.getByRole("alert")).toBeTruthy());
		expect(screen.getByText(/couldn't load incident data/i)).toBeTruthy();
	});

	it("retries and recovers after a failed fetch", async () => {
		let callCount = 0;
		vi.stubGlobal(
			"fetch",
			vi.fn((url: string) => {
				callCount++;
				if (callCount <= 3) return Promise.reject(new Error("network down"));
				if (url.includes("meta.json")) return Promise.resolve({ ok: true, json: async () => meta });
				return Promise.resolve({ ok: true, json: async () => [] });
			}),
		);
		render(<App />);
		await waitFor(() => expect(screen.getByRole("alert")).toBeTruthy());
		fireEvent.click(screen.getByRole("button", { name: /retry/i }));
		await waitFor(() => expect(screen.getByText(/summaries generated by/i)).toBeTruthy());
	});
});
