import { useEffect, useState } from "react";
import Dashboard from "../Dashboard/Dashboard";
import HowThisWorksLink from "../HowThisWorks/HowThisWorksLink";
import { fetchDashboardData } from "../../lib/dataSource";
import type { CoverageEntry, Incident, Meta } from "../../lib/types";
import * as s from "./App.css";

type State =
	| { status: "loading" }
	| { status: "error" }
	| { status: "ready"; meta: Meta; incidents: Incident[]; coverage: CoverageEntry[] };

export default function App() {
	const [state, setState] = useState<State>({ status: "loading" });

	function load() {
		setState({ status: "loading" });
		fetchDashboardData()
			.then((data) => setState({ status: "ready", ...data }))
			.catch(() => setState({ status: "error" }));
	}

	useEffect(load, []);

	if (state.status === "loading") return <LoadingSkeleton />;

	if (state.status === "error") {
		return (
			<div className={s.errorState} role="alert">
				Couldn't load incident data.
				<button onClick={load} className={s.retryButton}>
					Retry
				</button>
			</div>
		);
	}

	const { meta, incidents, coverage } = state;
	return (
		<>
			<div className={s.provenanceBar}>
				<span>
					Summaries generated by <code>{meta.default_model}</code>, prompt <code>{meta.default_prompt_version}</code>, schema{" "}
					<code>{meta.default_schema_version}</code> — exceptions flagged per incident
				</span>
				<span className={s.provenanceLink}>
					<HowThisWorksLink
						defaultModel={meta.default_model}
						defaultPromptVersion={meta.default_prompt_version}
						providerCount={coverage.length}
					/>
				</span>
			</div>

			<Dashboard incidents={incidents} coverage={coverage} dataAsOfIso={meta.generated_at_utc} />
		</>
	);
}

// No spinner attached to any number (spec §15) — plain pulsing placeholder
// blocks shaped like the regions they'll be replaced by.
function LoadingSkeleton() {
	return (
		<div role="status" aria-label="Loading incident data">
			<div className={s.skeletonBar} style={{ width: "60%" }} />
			<div className={s.skeletonStatsGrid}>
				<div className={s.skeletonStat} />
				<div className={s.skeletonStat} />
				<div className={s.skeletonStat} />
				<div className={s.skeletonStat} />
			</div>
			<div className={s.skeletonChart} />
			<div className={s.skeletonCards}>
				<div className={s.skeletonCard} />
				<div className={s.skeletonCard} />
				<div className={s.skeletonCard} />
			</div>
		</div>
	);
}
